// Generated by gencpp from file servo_control/Servo.msg
// DO NOT EDIT!


#ifndef SERVO_CONTROL_MESSAGE_SERVO_H
#define SERVO_CONTROL_MESSAGE_SERVO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servo_control
{
template <class ContainerAllocator>
struct Servo_
{
  typedef Servo_<ContainerAllocator> Type;

  Servo_()
    : velocity(0.0)
    , position(0.0)  {
    }
  Servo_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , position(0.0)  {
  (void)_alloc;
    }



   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::servo_control::Servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servo_control::Servo_<ContainerAllocator> const> ConstPtr;

}; // struct Servo_

typedef ::servo_control::Servo_<std::allocator<void> > Servo;

typedef boost::shared_ptr< ::servo_control::Servo > ServoPtr;
typedef boost::shared_ptr< ::servo_control::Servo const> ServoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servo_control::Servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servo_control::Servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servo_control::Servo_<ContainerAllocator1> & lhs, const ::servo_control::Servo_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servo_control::Servo_<ContainerAllocator1> & lhs, const ::servo_control::Servo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servo_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servo_control::Servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servo_control::Servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::Servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servo_control::Servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::Servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servo_control::Servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servo_control::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a872df59b68701da2b59c215ad257f0e";
  }

  static const char* value(const ::servo_control::Servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa872df59b68701daULL;
  static const uint64_t static_value2 = 0x2b59c215ad257f0eULL;
};

template<class ContainerAllocator>
struct DataType< ::servo_control::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servo_control/Servo";
  }

  static const char* value(const ::servo_control::Servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servo_control::Servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Velocity being sent to the servo\n"
"float64 velocity\n"
"float64 position\n"
;
  }

  static const char* value(const ::servo_control::Servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servo_control::Servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servo_control::Servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servo_control::Servo_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVO_CONTROL_MESSAGE_SERVO_H
